version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - ./gradlew clean buildZip
      - sam package
        --template-file template.yml
        --output-template-file package.yml
        --s3-bucket ungerw-codepipeline-eu-central123
artifacts:
  files:
    - package.yml
